version: '3.1'
services:
  
  proxy:
    image: kairos0ne/stories-stack-proxy
    networks:
      - nginx
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
      - target: 4433
        published: 443
        protocol: tcp
        mode: host
    healthcheck:
      disable: true
    configs:
      - source: nginx_config
        target: /etc/nginx/sites-enabled/default
  
  gui:
    image: kairos0ne/stories-stack-gui
    ports:
      - "8080:80"
    networks:
      - nginx

  api:
    image: kairos0ne/stories-stack-api
    ports:
      - "3000:3000"
    networks:
      - db
      - nginx

  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - db
    depends_on:
      - db

configs:
  nginx_config:
    file: ./configs/nginx_dev.conf

volumes:
  pg_data:

networks:
  nginx:
    driver: overlay
    attachable: true
  db:

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD.txt
  POSTGRES_USER:
    file: ./secrets/POSTGRES_USER.txt