version: '3'
services:
  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes: 
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    networks: 
      - db
      - nginx
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks: 
      - db
      - nginx
  gui:
    image: kairos0ne/stories-stack-gui
    networks:
      - nginx
      - db
    ports: 
      - "8080:80"
 
volumes: 
  pg_data:
  default.conf:
    

networks:
  nginx:
  db: