version: '3'
services:
  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes: 
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5431:5432
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes: 
  pg_data: